spring:
  kafka:
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500

  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_microservice
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

kafka:
  bootstrap-servers: localhost:9092
  group-id: microservice-group
  batch-size: 16384
  linger-ms: 5
  buffer-memory: 33554432
  retries: 3
  acks: all
  enable-idempotence: true
  max-poll-records: 500
  session-timeout-ms: 30000
  heartbeat-interval-ms: 3000
  auto-offset-reset: earliest

